#version 430
layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
// from computeShader

uniform samplerBuffer commandBuf;
uniform ivec4 dimens;
writeonly uniform uimageBuffer valuesBuf;



void main() {
  uvec3 pos = gl_GlobalInvocationID;
  uvec4 colorValue = uvec4(uint(0), uint(0), uint(texelFetch(commandBuf, int(pos.x)).x), uint(255));
  imageStore(valuesBuf, int(pos.y * uint(dimens.x) + pos.x), colorValue);
}
